outputs:
  - name: 'render front'
    type: blender_export
    dir: 'pcb'
    options:
      light:
        - name : 'light_1'
          energy: 0
          pos_x: '-size*3.33'
          pos_y: 'size*3.33'
          pos_z: 'size*5'
        - name : 'light_2'
          energy: 0
          pos_x: 0
          pos_y: 0
          pos_z: 1000
        - name : 'light_3'
          energy: 0
          pos_x: -50
          pos_y: -50
          pos_z: 300

      render_options:
        transparent_background: true
        samples: 10
        resolution_x: 720
        resolution_y: 1280
      point_of_view:
        - rotate_z: -90
          rotate_x: 0
          rotate_y: 0
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 1.05
      outputs:
        - type: render
        - output: 'front.png'
