outputs:
  - name: 'render front'
    type: blender_export
    dir: 'pcb'
    options:
      add_default_light: true
      light:
        type: 'SUN'
      render_options:
        transparent_background: true
        samples: 3

      point_of_view:
        - rotate_z: -90
          rotate_x: 20
          rotate_y: 0
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 1.5
      outputs:
        - type: render
        - output: 'front.png'
