outputs:
  - name: 'gerber files'
    comment: "Gerber"
    type: gerber
    dir: gerber
    options:
      output: '%i%I%v.%x'
      create_gerber_job_file: true
      gerber_job_file: 'job.%x'
      gerber_precision: 4.6

      # exclude_edge_layer: false
      # exclude_pads_from_silkscreen: false
      # use_aux_axis_as_origin: false
      # plot_footprint_refs: true
      # plot_footprint_values: true
      # force_plot_invisible_refs_vals: false
      # tent_vias: true
      # line_width: 0.15
      # subtract_mask_from_silk: true
      # use_protel_extensions: false
      # use_gerber_x2_attributes: true
      # use_gerber_net_attributes: false
      # output: '%f_%i.%x'
      
      # default options
      plot_sheet_reference: false

    # layers: all
    layers:
      - 'copper'
      - layer: 'F.Mask'
      - layer: 'F.Paste'
      - layer: 'F.Silkscreen'
      - layer: 'B.Mask'
      - layer: 'B.Paste'
      - layer: 'B.Silkscreen'
      - layer: 'Edge.Cuts'


