outputs:
  - name: 'render front'
    type: blender_export
    dir: 'pcb'
    options:
      add_default_light: true
      render_options:
        transparent_background: true
        samples: 10
        resolution_x: 720
        resolution_y: 1280
      point_of_view:
        - rotate_z: -90
          rotate_x: 0
          rotate_y: 0
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 1.05
      outputs:
        - type: render
        - output: 'front.png'
